"""Static results page (markdown) for the published run."""

from __future__ import annotations

from typing import Any


class Fmt:
    @staticmethod
    def num(value: Any, digits: int = 3) -> str:
        if value is None:
            return "n/a"
        if isinstance(value, bool):
            return "yes" if value else "no"
        if isinstance(value, float):
            return f"{value:.{digits}f}"
        return str(value)

    @staticmethod
    def rate(r: dict[str, Any]) -> str:
        if r.get("value") is None:
            return "n/a (0 trials)"
        return f"{r['value']:.3f} ({r['successes']}/{r['trials']}; Wilson 95% low {r['wilson_low']:.3f})"


class ResultsPage:
    @staticmethod
    def render(out: dict[str, Any], protocol: dict[str, Any]) -> str:
        m, v, cut = out["metrics"], out["verdict"], out["cutoffs"]
        bar = protocol["rules"]["bar"]
        lines = [
            "# Results: published run on synthetic test seed 202",
            "",
            f"**Verdict against the frozen bar: {v['verdict']}**"
            + (" (run invalid: no accuracy claim)" if v["run_invalid"] else ""),
            "",
            "Everything below is measured on synthetic Accounts generated by this repo. It says nothing about real CRM data,",
            "production performance, or any vendor.",
            "",
            f"- Run id: `{out['run_id']}`",
            f"- Freeze commit (bar and cutoffs committed and pushed before this run): `{out['freeze_commit']}`",
            f"- Prompt: `prompts/account_match.v1.md`, sha256 `{out['prompt_sha256']}`",
            f"- Requested model: `{protocol['rules']['model']['requested']}`; returned: "
            + ", ".join(f"`{k}` x{n}" for k, n in sorted(m["answers"]["returned_models"].items())),
            f"- Frozen cutoffs: Splink auto-merge at match weight >= {cut['splink_merge_weight']}; "
            f"AI merge at p >= {cut['ai_merge']}; AI no-match at p <= {cut['ai_nonmatch']}",
            f"- Estimated spend for this run: ${m['published_spend_usd']:.4f} (from token usage at list price)",
            "",
            "## Criteria",
            "",
            "| # | Criterion | Observed | Required | Result |",
            "|---|---|---|---|---|",
        ]
        for row in v["criteria"]:
            observed = row["observed"]
            if isinstance(observed, dict):
                observed = "; ".join(f"{k}={Fmt.num(x)}" for k, x in observed.items())
            else:
                observed = Fmt.num(observed)
            lines.append(f"| {row['criterion'][:1]} | {row['criterion'][2:]} | {observed} | {row['required']} | "
                         f"{'pass' if row['passed'] else 'FAIL'} |")
        b, c = m["baseline"], m["cascade"]
        lines += [
            "",
            "## Numbers",
            "",
            f"- Candidates after blocking: {m['candidates']}; true pairs: {m['true_pairs']}",
            f"- Blocking recall: {Fmt.rate(m['blocking_recall'])}",
            f"- Splink baseline auto-merge precision: {Fmt.rate(b['precision'])}",
            f"- Splink baseline auto-merge recall: {Fmt.rate(b['recall'])}",
            f"- Splink baseline review zone (p in [0.01, cutoff)): {b['review_size']} pairs; reachable recall {Fmt.num(b['reachable_recall'])}",
            f"- Cascade auto-merge precision: {Fmt.rate(c['precision'])}",
            f"- Cascade auto-merge recall: {Fmt.rate(c['recall'])}",
            f"- Cascade review queue: {m['review_queue_size']} pairs ({m['review_queue_size'] / m['candidates']:.1%} of candidates; "
            f"{m['review_queue_true_pairs']} of them true pairs); reachable recall {Fmt.num(m['cascade_reachable_recall'])}",
            f"- Cascade decisions: " + ", ".join(f"{k}={n}" for k, n in sorted(m["cascade_decisions"].items())),
            f"- Unseen family (rebrand_domain) recall: cascade {Fmt.rate(m['unseen_family_recall'])}; "
            f"baseline {Fmt.rate(m['unseen_family_recall_baseline'])}",
            f"- Missing/malformed answers: {m['answers']['missing']}/{m['answers']['calls']} "
            f"({m['answers']['missing_rate']:.2%}); version coverage {m['answers']['version_coverage']:.2%}; "
            f"model log run_valid={m['answers']['model_log_run_valid']}",
            f"- Calibration (repeat 1, {bar['calibration_bins']} bins, min count {bar['calibration_min_count']}): "
            f"{m['calibration']['met_bins']}/{m['calibration']['measured_bins']} measured bins met; "
            f"max |mean p - observed| = {Fmt.num(m['calibration']['max_abs_gap'])}",
            f"- Disguised-names arm ({m['disguised_names']['true_pairs_in_sample']} true pairs in a {m['disguised_pairs']}-pair sample): "
            f"recall {Fmt.num(m['disguised_names']['recall_main_repeat1'])} with names vs "
            f"{Fmt.num(m['disguised_names']['recall_disguised'])} disguised; flagged={m['disguised_names'].get('flagged')}",
            f"- Tokens: input {m['tokens']['input']}, output {m['tokens']['output']} (reasoning {m['tokens']['reasoning']})",
            "",
            "## Recall by corruption family (pairs where either record carries the family)",
            "",
            "| Family | Cascade | Baseline |",
            "|---|---|---|",
        ]
        for fam, r in m["family_recall"].items():
            lines.append(f"| {fam} | {Fmt.rate(r['cascade'])} | {Fmt.rate(r['baseline'])} |")
        lines += [
            "",
            "## Files",
            "",
            "- `results/metrics.json`: every number on this page",
            "- `results/review_queue.csv`: pairs routed to a human",
            "- `results/calibration.md`: calibration table",
            f"- `runs/{out['run_id']}/`: run log (with prompt hash), model version log, decision ledger (shadow then score), raw calls",
            "- `config/frozen/protocol.json`: the frozen bar and cutoffs",
            "",
        ]
        return "\n".join(lines)
